name: CI on demand

env:
  sfos_target: 4.5.0.16

on:
  workflow_dispatch:
    branches:
      - devel
#  push:
#    tags:
#      - '0.0.0'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: Prepare
      run: mkdir RPMS

#    - name: Build armv7hl
#      uses: robang74/github-sfos-apps-build@master
#      with:
#        release: ${{ env.sfos_target }}
#        arch: armv7hl

#    - name: Build i486
#      uses: robang74/github-sfos-apps-build@master
#      with:
#        release: ${{ env.sfos_target }}
#        arch: i486

    - name: Build aarch64
      uses: robang74/github-sfos-apps-build@master
      with:
        release: ${{ env.sfos_target }}
        arch: aarch64

    - name: Upload build result
      uses: actions/upload-artifact@v3
      with:
        name: rpm-build-result
        path: RPMS

    - name: Create release
      if: contains(github.ref, 'release')
      run: |
        set -x
        assets=()
        for asset in RPMS/*.rpm; do
          assets+=("-a" "$asset")
        done
        tag_name="${GITHUB_REF##*/}"
        hub release create "${assets[@]}" -m "$tag_name" "$tag_name"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
