#!/bin/bash

# TODO: hard-shutdown should trigger restore otherwise a
#       patch permanently applied to the filesystem can
#       break the next reboot in such a way the end-user
#       cannot repair it without technical assistence
#PM_ROOT_DIR="/"

source $(dirname $0)/pm_patch.env apply "$@" 2>&1 || exit 1

#
# The main function that controls all the magic stuff
#

safety_check_patch
[ -n "$MANGLE_CANDIDATES" ] && mangle_libpath
test_if_applied && success
verify_text_patch
install_text_patch
create_backup_patch
success
