#!/bin/bash

# TODO: hard-shutdown should trigger restore otherwise a
#       patch permanently applied to the filesystem can
#       break the next reboot in such a way the end-user
#       cannot repair it without technical assistence
#PM_ROOT_DIR="/"

source $(dirname $0)/pm_patch.env unapply "$@" 2>&1 || exit 1

#                                                                 
# The main function that controls all the magic stuff                             
#                                              
                                                                               
safety_check_patch
test_if_applied
remove_text_patch
clean_backup_patch
success
